spring:
  application:
    name: service0
  cloud:
    config:
      uri: http://localhost:8084/
      profile: test

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8022
server:
  port: 8022

feign:
  hystrix:
    enabled: true
